name: ContractrPro CI

on: 
    # Runs the inside pull requests to the main and dev branches
    pull_request: 
        branches: [main, dev]

jobs:
    build:
        # Uses a Ubuntu Docker VM to run the application on
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with: 
                node-version: "18.14.0"
                cache: "npm"
            - name: Install Dependencies 
              run: npm ci
            - name: Check for bugs
              run: npm run lint
            - name: Check for code formatting
              run: npm run prettier
            - name: Build
              run: npm run build
            - name: Test with Cypress
              uses: cypress-io/github-action@v2
              with:
                  start: npm start

