name: ContractrPro Client

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - "docs/**"
      - "client/**"
      - ".github/workflows/**"
  # Runs the inside pushes to the main and dev branches
  push:
    branches: [ main, dev ]
    paths:
      - "docs/**"
      - "client/**"
      - ".github/workflows/**"
jobs:
  generate-markdown:
    # Only runs if the triggering actor is not the GitHub Actions bot
    if: github.triggering_actor != 'github-actions[bot]'
    permissions:
      contents: write
    # Uses a Ubuntu Docker VM to run the application on
    runs-on: ubuntu-latest
    environment: "Dev Env"
    defaults:
      run:
        working-directory: .github/scripts
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - name: Setup Node for API
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
      - name: Generate Markdown docs for components
        run: node commentsToMarkdown.js
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generated markdown docs
          branch: ${{ github.head_ref }}
  build:
    # Only runs if the triggering actor is not the GitHub Actions bot and is a push to the main or dev branch
    if: github.triggering_actor != 'github-actions[bot]' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
    permissions:
      contents: write
    # Uses a Ubuntu Docker VM to run the application on
    runs-on: ubuntu-latest
    environment: "Dev Env"
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - name: Setup Node for API
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
          cache: "npm"
          cache-dependency-path: ./client/package-lock.json
      - name: Install Dependencies
        run: npm ci --no-optional
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t watchdogsrox/contractrpro-client:latest .
      - name: Push Docker image
        run: docker push watchdogsrox/contractrpro-client:latest
  deploy:
    # Sends a webhook to Portainer to deploy the client stack. URL is stored in the secret PORTAINER_CLIENT_WEBHOOK_URL
    needs: [ build ]
    environment: "Dev Env"
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Portainer deploy webhook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.PORTAINER_CLIENT_WEBHOOK_URL }}