name: ContractrPro CI

on:
    # Runs the inside pull requests to the main and dev branches
    pull_request:
        branches: [main, dev]

jobs:
    formatting:
        # Uses a Ubuntu Docker VM to run the application on
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                node-version: "18.16.0"
                cache: "npm"
            - name: Install Dependencies
              working-directory: ./api
              run: npm ci
            - name: Check for bugs
              working-directory: ./api
              run: npm run lint
            - name: Check for code formatting
              working-directory: ./api
              run: npm run prettier
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply formatting changes
                  branch: ${{ github.head_ref }}
